[behave]

# Allure integration
format = allure_behave.formatter:AllureFormatter
outfiles = reports/allure-results

# Generate JUnit XML reports
;junit = true
;junit_directory = reports

# Define the default formatting style (e.g., pretty, progress, plain)
default_format = pretty

# Run only scenarios containing a specific tag by default
# default_tags = @smoke and not @wip

[behave.userdata]
# Define custom variables accessible globally via `context.config.userdata`
BASE_URL=https://demo.opencartmart.com/ordercoupon/index.php